services:

  radiator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radiator
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./radiator.conf:/etc/radiator/radiator.conf:ro
      - ./dictionary:/opt/radiator/radiator/dictionary:ro
      - ./certs:/etc/radiator/certs:ro
      - ./logs/radiator.log:/var/log/radiator/radiator.log
      - ./session_hook.pl:/etc/radiator/session_hook.pl:ro
    environment:
      DB_HOST: 10.42.4.5
      DB_PORT: 5432
      DB_USER: radiator
      DB_PASSWORD: ap0ll0ap0ll0
      DB_NAME: radius
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
